#!/bin/sh
mkfifo /tmp/iqpipe > /dev/null 2>&1
xterm -title control -geometry 120x12 -e "~/bin/control -f 1296298000 -m usb -t 10" &
xterm -title funcube -geometry 100x8 -e "~/bin/funcube -v -v -g 50 > /tmp/iqpipe" &
~/bin/radio -f 147435000 -m fm -S null -r 24000 -e < /tmp/iqpipe | opusenc --quiet --max-delay 100 --ignorelength --bitrate 64 - -






